"""配置出厂默认冻结(票 G):任何出厂默认值被悄悄改动都会让本测试变红。

不 mock:直接读取真实 Settings.model_fields。新增字段必须同步登记到 FROZEN_DEFAULTS,
否则下面的全字段枚举断言会报出未登记字段。
"""

from lantai.core.settings import Settings

FROZEN_DEFAULTS = {
    'LANTAI_HOME': '',
    'REMEMBRANCE_HOME': '',
    'HOST': '127.0.0.1',
    'PORT': 8767,
    'LANTAI_RUN_SCHEDULER': True,
    'DATABASE_URL': '',
    'OPENAI_API_KEY': '',
    'OPENAI_BASE_URL': 'https://api.openai.com/v1',
    'LLM_MODEL': 'gpt-4o-mini',
    'VISION_MODEL': '',
    'MEDIA_DATA_URI_MAX_BYTES': 10485760,
    'EMBED_MODEL': 'BAAI/bge-m3',
    'LLM_MAX_CONCURRENCY': 4,
    'LLM_ACQUIRE_TIMEOUT': 30.0,
    'MCP_LOOP_GUARD_ENABLED': True,
    'MCP_LOOP_GUARD_THRESHOLD': 5,
    'MCP_LOOP_GUARD_WINDOW_S': 60.0,
    'MCP_LOOP_GUARD_COOLDOWN_S': 30.0,
    'INGEST_CRON_MINUTES': 60,
    'EVOLVE_CRON_MINUTES': 30,
    'FORGET_CRON_HOURS': 24,
    'GATE_MIN_EXTRACTOR_CONF': 0.55,
    'PROMOTE_SEMANTIC_MIN_SOURCES': 2,
    'PROCEDURAL_ROLLBACK_HOURS': 24,
    'WORKING_MEMORY_TTL_DAYS': 60,
    'CANDIDATE_TTL_DAYS': 7,
    'CANDIDATE_MIN_CONFIDENCE': 0.15,
    'DIALOGUE_ENABLED': True,
    'DIALOGUE_MIN_CHARS': 8,
    'DIALOGUE_MIN_EXTRACTOR_CONF': 0.55,
    'CANDIDATE_TTL_CRON_HOURS': 24,
    'DIGEST_ENABLED': True,
    'DIGEST_CRON_HOUR': 22,
    'DIGEST_OUTPUT_DIR': '',
    'LANE_DECAY_PROFILES': {'fact': {'base_s': 30, 'importance_boost': 40}, 'rule': {'base_s': 60, 'importance_boost': 30}, 'experience': {'base_s': 10, 'importance_boost': 15}, 'preference': {'base_s': 15, 'importance_boost': 20}, 'chat': {'base_s': 3, 'importance_boost': 5}, 'general': {'base_s': 10, 'importance_boost': 15}, 'distill': {'base_s': 30, 'importance_boost': 15}},
    'LANE_RETRIEVAL_BOOST': {'fact': 1.3, 'rule': 1.2, 'experience': 1.0, 'preference': 1.1, 'chat': 0.7, 'general': 1.0, 'distill': 1.0},
    'DEFAULT_LANE': 'general',
    'RAW_MEMORY_DEFAULT_LANE': 'general',
    'VERBATIM_IN_RECALL': False,
    'CONFLICT_RULES_ENABLED': True,
    'CONFLICT_MUTEX_RULES': [{'name': 'status_switch', 'pair': ['启用', '禁用']}, {'name': 'toggle', 'pair': ['已开启', '已关闭']}, {'name': 'version_change', 'pair': ['版本 1', '版本 2']}],
    'CONFLICT_ANTONYM_ENABLED': True,
    'CONFLICT_ANTONYM_RULES': [{'name': 'like_hate', 'pair': ['喜欢', '讨厌']}, {'name': 'support_oppose', 'pair': ['支持', '反对']}, {'name': 'agree_reject', 'pair': ['同意', '拒绝']}, {'name': 'allow_forbid', 'pair': ['允许', '禁止']}, {'name': 'online_offline', 'pair': ['在线', '离线']}, {'name': 'free_paid', 'pair': ['免费', '付费']}, {'name': 'public_private', 'pair': ['公开', '私密']}, {'name': 'start_stop', 'pair': ['开始', '停止']}],
    'CONFLICT_SALIENCE_MIN_IMPORTANCE': 0.4,
    'CONFLICT_SALIENCE_DEMOTE_STEP': 0.2,
    'CONFLICT_CHECK_TOP_K': 10,
    'GATE_NOVELTY_THRESHOLD': 0.15,
    'GATE_NOVELTY_SAMPLE_SIZE': 50,
    'CONFLICT_NEGATION_ENABLED': True,
    'CONFLICT_NEGATION_PAIRS': [{'name': 'be_notbe', 'pair': ['是', '不是']}, {'name': 'can_cannot', 'pair': ['会', '不会']}, {'name': 'able_unable', 'pair': ['能', '不能']}, {'name': 'have_not', 'pair': ['有', '没有']}, {'name': 'want_not', 'pair': ['要', '不要']}],
    'MONITOR_ENABLED': True,
    'MONITOR_REQUEST_BUFFER': 5000,
    'MONITOR_BUCKET_MINUTES': 720,
    'MONITOR_PERSIST_SLOW_MS': 800.0,
    'MONITOR_PERSIST_SAMPLE': 20,
    'MONITOR_RETENTION_DAYS': 7,
    'MONITOR_FLUSH_SECONDS': 5.0,
    'MONITOR_WINDOW_SECONDS': 900,
    'MONITOR_SERIES_MINUTES': 60,
    'MONITOR_EXCLUDE_PATHS': ('/ui/assets', '/favicon.ico'),
    'MONITOR_ALERT_ERROR_RATE': 0.05,
    'MONITOR_ALERT_P95_MS': 3000.0,
    'MONITOR_ALERT_ZERO_RECALL_RATE': 0.35,
    'MONITOR_ALERT_BACKLOG': 200,
    'MONITOR_ALERT_DB_MB': 1024.0,
    'MONITOR_WORKER_GRACE_FACTOR': 0.25,
    'MONITOR_WORKER_CRITICAL_FACTOR': 2.0,
    'API_KEY': '',
    'FEATURE_OBSIDIAN': False,
    'FEATURE_WIKI': True,
    'FEATURE_VISION': False,
    'FEATURE_KAOGONG': False,
    'FEATURE_SCENES': False,
    'FEATURE_TERMINAL': True,
    'FEATURE_WORK_ITEMS': True,
    'FEATURE_CRYSTALS': True,
    'RERANKER_MODEL': 'BAAI/bge-reranker-v2-m3',
    'RERANKER_BASE_URL': 'https://api.siliconflow.cn/v1',
    'RERANKER_ENABLED': True,
    'RERANKER_TIMEOUT': 30,
    'RERANKER_RETRY_DELAY': 1.0,
    'RERANKER_CANDIDATE_MULTIPLIER': 2,
    'INTENT_CANDIDATE_SIZES': {'fact_lookup': 10, 'procedural': 15, 'exploratory': 20},
    'DEFAULT_INTENT': 'fact_lookup',
    'VECTOR_STORE_TYPE': 'chromadb',
    'TEMPORAL_CURRENT_STRICT': False,
    'TEMPORAL_ASOF_STRICT': False,
    'TEMPORAL_FUZZY_PENALTY': 0.8,
    'CHROMADB_PATH': '',
    'GATE_CACHE_TTL': 15.0,
    'COALESCE_ENABLED': False,
    'LANE_COALESCE_PROFILES': {'fact': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}, 'rule': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}, 'experience': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}, 'preference': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}, 'chat': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}, 'general': {'idle_timeout': 4.0, 'window': 12.0, 'max_parts': 8, 'max_chars': 2000}},
    'ARCHIVE_DECAY_THRESHOLD': 0.01,
    'CHECKPOINT_MAX_SESSIONS': 5,
    'CHECKPOINT_STALENESS_DAYS': 30,
    'CHECKPOINT_MIN_CONTENT': 3,
    'CHECKPOINT_MAX_CONTENT': 600,
    'DEDUP_MERGE_THRESHOLD': 0.9,
    'DEDUP_UPDATE_THRESHOLD': 0.65,
    'DEDUP_PRESCREEN_MERGE': 0.95,
    'DEDUP_STRUCTURAL_ENABLED': True,
    'DEDUP_STRUCTURAL_LLM_ENABLED': True,
    'DEDUP_ANCHOR_HIGH': 0.6,
    'DEDUP_ANCHOR_LOW': 0.3,
    'DEDUP_EXTRA_ANCHOR_LIMIT': 2,
    'SHELL_HOOK_TIMEOUT': 2,
    'SHELL_HOOK_DIALOGUE_TIMEOUT': 30.0,
    'SHELL_HOOK_TOP_K': 5,
    'SHELL_HOOK_MIN_CHARS': 3,
    'SHELL_HOOK_MAX_CHARS_PER_MEMORY': 200,
    'SHELL_HOOK_MAX_TOTAL_CHARS': 1500,
    'SHELL_HOOK_TOOLS_GUIDE': True,
    'SHELL_HOOK_INJECT_DATE': 'day',
    'SHELL_HOOK_OFFLOAD_CHARS': 2000,
    'OFFLOAD_OUTPUT_DIR': '',
    'FTS_BM25_GRAM_TOKENIZE': True,
    'DATA_FENCE_ENABLED': True,
    'INJECTION_GUARD_ENABLED': True,
    'SECRET_GUARD_MODE': 'off',
    'IDEMPOTENCY_TTL_DAYS': 7,
    'WIKI_ENABLED': True,
    'WIKI_OUTPUT_DIR': '',
    'WIKI_OVERVIEW_LLM': True,
    'WIKI_PAGE_MAX_MEMBERS': 50,
    'WIKI_MEMBER_CHARS': 120,
    'WIKI_RELATED_TOP': 3,
    'AGENT_LANE_BINDINGS': {},
    'IMPORT_MAX_LINES': 5000,
    'SCENE_LAYER_ENABLED': False,
    'SCENE_CLUSTER_THRESHOLD': 0.78,
    'SCENE_REBUILD_LLM_NAMING': True,
    'SHELL_HOOK_MAX_CHARS_PER_SCENE': 400,
    'SCENE_MAX_MEMBERS_SHOWN': 8,
    'RECALL_MONITOR_WINDOW_DAYS': 7,
    'SSRF_ALLOWED_SCHEMES': ('http', 'https'),
    'SSRF_MAX_REDIRECTS': 3,
    'SSRF_MAX_BYTES': 5242880,
    'RSS_TIMEOUT': 30,
    'BACKUP_MANIFEST_VERSION': '0.3.3',
    'RETRIEVAL_W_VECTOR': 0.6,
    'RETRIEVAL_W_BM25': 0.25,
    'RETRIEVAL_W_FTS': 0.05,
    'RETRIEVAL_W_DECAY': 0.1,
    'SUPERSEDES_ORDERING_ENABLED': True,
    'SUPERSEDES_DEMOTE_EPSILON': 1e-06,
    'ECHO_SUPPRESS_ENABLED': False,
    'ECHO_SUPPRESS_WINDOW_SECONDS': 900,
    'MMR_ENABLED': False,
    'MMR_LAMBDA': 0.7,
    'ERRSIG_BONUS': 0.1,
    'DISTILL_MIN_MEMORIES': 3,
    'DISTILL_MAX_SOURCE': 24,
    'DISTILL_ENABLED': True,
    'AUTODREAM_ENABLED': True,
    'AUTODREAM_MIN_CLUSTER': 2,
    'AUTODREAM_MAX_DAILY': 10,
    'AUTODREAM_MIN_CONFIDENCE': 0.5,
    'AUTODREAM_CRON_DAYS': 7,
    'CONSOLIDATION_AUDIT_MODE': 'off',
    'CONSOLIDATION_SHADOW_MAX_DAYS': 7,
    'CONSOLIDATION_REJECTED_COOLDOWN_DAYS': 30,
    'CONSOLIDATION_AGGREGATE_MASTER_MIN_SOURCES': 3,
    'CONSOLIDATION_MIN_CLUSTER_SIZE': 3,
    'CONSOLIDATION_PRUNE_THRESHOLD': 0.05,
    'CRYSTAL_ENABLED': True,
    'CRYSTAL_MIN_CLUSTER': 3,
    'CRYSTAL_MAX_DAILY': 10,
    'FTS_RECALL_TOP_K': 20,
    'ALLOWED_API_HOSTS': ['api.openai.com', 'api.siliconflow.cn'],
    'RERANKER_API_KEY': '',
    'PARAM_ADVICE_ENABLED': True,
    'PARAM_ADVICE_CRON_MINUTES': 30,
    'PARAM_ADVICE_MIN_PAPERS': 5,
    'PARAM_ADVICE_MAX_WAIT_DAYS': 7,
    'PARAM_ADVICE_MAX_BATCH_SIZE': 10,
    'PARAM_ADVICE_MIN_CONFIDENCE': 0.85,
    'PARAM_ADVICE_MAX_CHANGES': 6,
    'PARAM_ADVICE_MAX_RETRIES': 3,
    'PARAM_ADVICE_PROCESSING_STALE_MINUTES': 120,
    'PARAM_OVERRIDE_REFRESH_SECONDS': 5.0,
    'PAPER_SIGNAL_ENABLED': True,
    'PAPER_SEASONED_DAYS': 60,
    'TIER_WEIGHT': {'A': 1.0, 'B': 0.97, 'C': 0.93, 'D': 0.0},
    'QUORUM_BY_TIER': {'A': 1, 'B': 1, 'C': 2},
    'DELTA_BUDGET_FACTOR': {'A': 1.0, 'B': 0.7, 'C': 0.5},
    'OBSERVATION_DAYS_BY_TIER': {'A': 3, 'B': 5, 'C': 7},
    'PAPER_STALE_WARN_MONTHS': 18,
    'PAPER_STALE_BLOCK_MONTHS': 36,
    'SUGGESTION_PENDING_TTL_DAYS': 30,
    'PARAM_OVERRIDE_REVIEW_DAYS': 90,
    'EVAL_QUERYSET_SIZE': 200,
    'EVAL_QUERYSET_WINDOW_DAYS': 90,
    'EVAL_QUERYSET_TTL_DAYS': 180,
    'EVAL_MIN_SAMPLES': 200,
    'EVAL_MIN_FEEDBACK_SAMPLES': 30,
    'EVAL_TOPK': 10,
    'OBSERVATION_MAX_DAYS': 21,
    'SHADOW_AUTO_ROLLBACK_ENABLED': True,
    'MAX_ACTIVE_SHADOW_WINDOWS': 1,
    'SHADOW_OBSERVE_DAYS': 7,
    'SHADOW_CHECK_INTERVAL_SECONDS': 3600,
    'CONTRADICTION_QUORUM_BUMP': 1,
    'PENALTY_FAIL_STREAK': 2,
    'PENALTY_FAIL_RATE': 0.5,
    'PENALTY_MIN_SAMPLES': 3,
    'PENALTY_TTL_DAYS': 180,
    'REFLECT_ENABLED': True,
    'REFLECT_CRON_HOUR': 22,
    'REFLECT_MAX_BATCH': 20,
    'REFLECT_OBSERVATION_WINDOW_DAYS': 14,
    'REFLECT_OBSERVATION_REQUIRED_RUNS': 7,
    'REFLECT_IMPORTANCE_POOL': 5.0,
    'REFLECT_IMPORTANCE_WINDOW_DAYS': 7,
    'REFLECT_AUTO_APPLY': False,
    'REFLECT_AUTO_APPLY_CONF': 0.7,
    'REFLECT_MIN_CONFIDENCE': 0.5,
    'REFLECT_MIN_USE_COUNT': 3,
    'REFLECT_LOW_HELPFUL_RATIO': 0.3,
    'REFLECT_STALE_AGE_DAYS': 30,
    'REFLECT_STALE_IMPORTANCE': 0.4,
    'REFLECT_STALE_SCAN_ENABLED': False,
    'DIGEST_CONF_BUCKETS': [('0.5-0.6', 0.5, 0.6), ('0.6-0.7', 0.6, 0.7), ('0.7-0.8', 0.7, 0.8), ('0.8-0.9', 0.8, 0.9), ('0.9-1.0', 0.9, 1.0)],
}


def test_every_setting_field_is_registered():
    unregistered = set(Settings.model_fields) - set(FROZEN_DEFAULTS)
    assert not unregistered, f"新增配置字段未登记到 FROZEN_DEFAULTS: {sorted(unregistered)}"


def test_registered_defaults_match_model_fields():
    drift = {
        name: (Settings.model_fields[name].default, expected)
        for name, expected in FROZEN_DEFAULTS.items()
        if Settings.model_fields[name].default != expected
    }
    assert not drift, f"出厂默认值漂移: {drift}"
